-- Print all the NLS parameters for the database, instance and session
SELECT DB.PARAMETER, DB.VALUE "DATABASE", I.VALUE "INSTANCE", S.VALUE
    "SESSION"
FROM NLS_DATABASE_PARAMETERS DB, NLS_INSTANCE_PARAMETERS I,
    NLS_SESSION_PARAMETERS S
WHERE DB.PARAMETER=I.PARAMETER(+) AND DB.PARAMETER=S.PARAMETER(+)
ORDER BY 1;



-- Checking possible values of certain parameters
SELECT * FROM V$NLS_VALID_VALUES WHERE parameter = 'LANGUAGE';
SELECT * FROM V$NLS_VALID_VALUES WHERE parameter = 'TERRITORY';



-- Parameter change
ALTER SESSION SET NLS_CALENDAR = 'GREGORIAN';
ALTER SESSION SET NLS_CURRENCY = 'zł';
ALTER SESSION SET NLS_DUAL_CURRENCY = 'PLN';
ALTER SESSION SET NLS_DATE_FORMAT = 'DD.MM.YYYY';
ALTER SESSION SET NLS_DATE_LANGUAGE = 'POLISH';
ALTER SESSION SET NLS_LANGUAGE = 'POLISH';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = ',.';
ALTER SESSION SET NLS_TERRITORY = 'POLAND';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'DD.MM.YYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'DD.MM.YYYY HH24:MI:SS TZR';



-- Testing the modified paramteres
-- Test 1: NLS_CALENDAR
SELECT TO_CHAR(SYSDATE, 'YYYY Month DD Day', 'NLS_CALENDAR = ''GREGORIAN''') AS "Kalendarz (GREGORIAN)" FROM dual;

-- Test 2: NLS_CURRENCY
SELECT TO_CHAR(1234.56, 'L9999.99') AS "Waluta (NLS_CURRENCY)" FROM dual;

-- Test 3: NLS_DATE_FORMAT
SELECT SYSDATE AS "Data (DD.MM.YYYY)" FROM dual;

-- Test 4: NLS_DATE_LANGUAGE
SELECT TO_CHAR(SYSDATE, 'Day, DD Month YYYY') AS "Data po polsku (NLS_DATE_LANGUAGE)" FROM dual;

-- Test 5: NLS_DUAL_CURRENCY (jeśli obsługiwane)
SELECT TO_CHAR(1234.56, 'C9999.99') AS "Waluta alternatywna (DUAL_CURRENCY)" FROM dual;

-- Test 6: NLS_LANGUAGE
SELECT VALUE AS "Język sesji" FROM NLS_SESSION_PARAMETERS WHERE PARAMETER = 'NLS_LANGUAGE';

-- Test 7: NLS_NUMERIC_CHARACTERS
SELECT TO_CHAR(1234.56, '9G999D99') AS "Liczba PL (NLS_NUMERIC_CHARACTERS)" FROM dual;

-- Test 8: NLS_TERRITORY
SELECT VALUE AS "Terytorium sesji" FROM NLS_SESSION_PARAMETERS WHERE PARAMETER = 'NLS_TERRITORY';

-- Test 9: NLS_TIMESTAMP_FORMAT
SELECT SYSTIMESTAMP AS "Znacznik czasu (TIMESTAMP_FORMAT)" FROM dual;

-- Test 10: NLS_TIMESTAMP_TZ_FORMAT
SELECT TO_CHAR(SYSTIMESTAMP, 'DD.MM.YYYY HH24:MI:SS TZR') AS "Znacznik + strefa (TZ_FORMAT)" FROM dual;



-- Print all the NLS parameters for the database, instance and session
SELECT DB.PARAMETER, DB.VALUE "DATABASE", I.VALUE "INSTANCE", S.VALUE
    "SESSION"
FROM NLS_DATABASE_PARAMETERS DB, NLS_INSTANCE_PARAMETERS I,
    NLS_SESSION_PARAMETERS S
WHERE DB.PARAMETER=I.PARAMETER(+) AND DB.PARAMETER=S.PARAMETER(+)
ORDER BY 1;

