-- Create 3 containers inside CDB$TOOR, PDB_Piasek_1, PDB_Piasek_2, PDB_Bazan_3
-- Each container has set a different NLS_LANGUAGE and NLS_TERRITORY (PL, EN, USA)

alter session set "_ORACLE_SCRIPT"=true;



-- Print the current container name and it's ID number
SHOW CON_NAME;
SHOW CON_ID;



-- Print info about the currently available containers in the database
SELECT NAME, CON_ID, DBID, CON_UID, GUID FROM V$CONTAINERS ORDER BY CON_ID;
SELECT PDB_ID, PDB_NAME, STATUS FROM DBA_PDBS ORDER BY PDB_ID;
show pdbs;



-- Create the containers

ALTER SESSION SET CONTAINER=CDB$ROOT;

-- PDB_Piasek_1
CREATE PLUGGABLE DATABASE PDB_Piasek_1
ADMIN USER admin_pdb_piasek_1 IDENTIFIED BY haslo
FILE_NAME_CONVERT = (
  '/opt/oracle/oradata/XE/pdbseed/',
  '/opt/oracle/oradata/XE/pdb_piasek_1/'
);

-- Open the container with the start of the database
ALTER PLUGGABLE DATABASE PDB_Piasek_1 SAVE STATE;

ALTER PLUGGABLE DATABASE PDB_Piasek_1 OPEN;

-- PDB_Piasek_2
CREATE PLUGGABLE DATABASE PDB_Piasek_2
ADMIN USER admin_pdb_piasek_2 IDENTIFIED BY haslo
FILE_NAME_CONVERT = (
  '/opt/oracle/oradata/XE/pdbseed/',
  '/opt/oracle/oradata/XE/pdb_piasek_2/'
);

-- Open the container with the start of the database
ALTER PLUGGABLE DATABASE PDB_Piasek_2 SAVE STATE;

ALTER PLUGGABLE DATABASE PDB_Piasek_2 OPEN;


-- PDB_Bazan_3
CREATE PLUGGABLE DATABASE PDB_Bazan_3
ADMIN USER admin_pdb_bazan_3 IDENTIFIED BY haslo
FILE_NAME_CONVERT = (
  '/opt/oracle/oradata/XE/pdbseed/',
  '/opt/oracle/oradata/XE/pdb_bazan_3/'
);

-- Open the container with the start of the database
ALTER PLUGGABLE DATABASE PDB_Bazan_3 SAVE STATE;

ALTER PLUGGABLE DATABASE PDB_Piasek_3 OPEN;


-- Setting up NLS_LANGUAGE and NLS_TERRITORY in the containers

-- PDB_Piasek_1
ALTER SESSION SET CONTAINER=PDB_Piasek_1;

CREATE OR REPLACE TRIGGER trg_set_nls_language_piasek1
AFTER LOGON ON DATABASE
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_LANGUAGE = ''POLISH'' NLS_TERRITORY = ''POLAND''';
END;
/


-- PDB_Piasek_2
ALTER SESSION SET CONTAINER=PDB_Piasek_2;

CREATE OR REPLACE TRIGGER trg_set_nls_language_piasek2
AFTER LOGON ON DATABASE
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_LANGUAGE = ''ENGLISH'' NLS_TERRITORY = ''UNITED KINGDOM''';
END;
/


-- PDB_Bazan_3
ALTER SESSION SET CONTAINER=PDB_Bazan_3;

CREATE OR REPLACE TRIGGER trg_set_nls_language_bazan3
AFTER LOGON ON DATABASE
BEGIN
  EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_LANGUAGE = ''AMERICAN'' NLS_TERRITORY = ''AMERICA''';
END;
/


-- PDB, CDB or the whole Oracle instance needs to be restarted for this to take effect
ALTER SESSION SET CONTAINER=CDB$ROOT;

ALTER PLUGGABLE DATABASE PDB_Piasek_1 CLOSE IMMEDIATE;
ALTER PLUGGABLE DATABASE PDB_Piasek_1 OPEN;

ALTER PLUGGABLE DATABASE PDB_Piasek_2 CLOSE IMMEDIATE;
ALTER PLUGGABLE DATABASE PDB_Piasek_2 OPEN;

ALTER PLUGGABLE DATABASE PDB_Bazan_3 CLOSE IMMEDIATE;
ALTER PLUGGABLE DATABASE PDB_Bazan_3 OPEN;



-- Checking if the changes took place for each container individually
SELECT NAME, OPEN_MODE FROM V$PDBS;


-- PDB_Piasek_1
ALTER SESSION SET CONTAINER=PDB_Piasek_1;
SHOW CON_NAME;

SELECT *
FROM NLS_SESSION_PARAMETERS
WHERE PARAMETER IN ('NLS_LANGUAGE', 'NLS_TERRITORY');


-- PDB_Piasek_2
ALTER SESSION SET CONTAINER=PDB_Piasek_2;
SHOW CON_NAME;

SELECT *
FROM NLS_SESSION_PARAMETERS
WHERE PARAMETER IN ('NLS_LANGUAGE', 'NLS_TERRITORY');


-- PDB_Bazan_3
ALTER SESSION SET CONTAINER=PDB_Bazan_3;
SHOW CON_NAME;

SELECT *
FROM NLS_SESSION_PARAMETERS
WHERE PARAMETER IN ('NLS_LANGUAGE', 'NLS_TERRITORY');



-- In case of launching the script again, close all the containers and drop them
-- ALTER PLUGGABLE DATABASE PDB_Piasek_1 CLOSE IMMEDIATE;
-- ALTER PLUGGABLE DATABASE PDB_Piasek_2 CLOSE IMMEDIATE;
-- ALTER PLUGGABLE DATABASE PDB_Bazan_3 CLOSE IMMEDIATE;
-- DROP PLUGGABLE DATABASE PDB_Piasek_1 INCLUDING DATAFILES;
-- DROP PLUGGABLE DATABASE PDB_Piasek_2 INCLUDING DATAFILES;
-- DROP PLUGGABLE DATABASE PDB_Bazan_3 INCLUDING DATAFILES;



-- This way of changing PDB parameters doesn't work in Oracle SQL 21c
-- ALTER SYSTEM SET NLS_LANGUAGE = 'POLISH' SCOPE = SPFILE;
-- ALTER SYSTEM SET NLS_TERRITORY = 'POLAND' SCOPE = SPFILE;

